const objects = [
  "favorite animal",
  "favorite hobby",
  "favorite food",
  "dream superpower",
  "favorite TV show",
  "favorite singer",
  "favorite music genre",
  "worst subject",
  "hidden talent",
  "meme that you think is the funniest",
  "childhood icon",
  "favorite cartoon",
  "favourite sport",
  "favourite movie",
  "significant other",
  "worst experience at a restaurant",
  "best place to eat chicken",
  "favourite mall",
  "dream job",
  "idea of God",
  "version of Michael Jackson",
  "favourite single-player game",
  "smallest object on your table now",
  "largest object on your table now",
  "current location",
  "hideous legs",
  "idea of a cat",
  "brand new species of animal",
];

module.exports = objects;
